### ISSUE TITLE
Module 'ssl.config' not found

### ISSUE THREAD

**Issue by chris-jansson** [ignacio/LuaOAuth#17]
Hi there,

I'm getting an error just trying to require this module. I installed OAuth with LuaRocks and OpenSSL with Homebrew. Any ideas where this `ssl.config` module is?

    /usr/local/share/lua/5.1/ssl.lua:11: module 'ssl.config' not found:No LuaRocks module found for ssl.config
	    no field package.preload['ssl.config']
	    no file './ssl/config.lua'
	    no file './ssl/config/init.lua'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/site/lualib/ssl/config.ljbc'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/site/lualib/ssl/config/init.ljbc'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/lualib/ssl/config.ljbc'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/lualib/ssl/config/init.ljbc'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/site/lualib/ssl/config.lua'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/site/lualib/ssl/config/init.lua'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/lualib/ssl/config.lua'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/lualib/ssl/config/init.lua'
	    no file './ssl/config.lua'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/luajit/share/luajit-2.1.0-beta3/ssl/config.lua'
	    no file '/usr/local/share/lua/5.1/ssl/config.lua'
	    no file '/usr/local/share/lua/5.1/ssl/config/init.lua'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/luajit/share/lua/5.1/ssl/config.lua'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/luajit/share/lua/5.1/ssl/config/init.lua'
	    no file '/usr/local/opt/kong/share/lua/5.1/ssl/config.lua'
	    no file '/usr/local/opt/kong/share/lua/5.1/ssl/config/init.lua'
	    no file './csrc/ssl/config.so'
	    no file './csrc/ssl/config/ssl/config.so'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/site/lualib/ssl/config.so'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/lualib/ssl/config.so'
	    no file './ssl/config.so'
	    no file '/usr/local/lib/lua/5.1/ssl/config.so'
	    no file '/usr/local/Cellar/openresty/1.13.6.2/luajit/lib/lua/5.1/ssl/config.so'
	    no file '/usr/local/lib/lua/5.1/loadall.so'
	    no file '/usr/local/opt/kong/lib/lua/5.1/ssl/config.so'
	    no module 'ssl.config' in file '/usr/local/lib/lua/5.1/ssl.so'

    stack traceback:
	    /usr/local/share/lua/5.1/ssl.lua:11: in main chunk

**Comment by ignacio** [comment]
Hi. `ssl.config` is part of [LuaSec](https://github.com/brunoos/luasec). It should be found in ssl.so, afaik. This is the [part of the code](https://github.com/brunoos/luasec/blob/master/src/config.c#L15) where it is exported.
I would check [LuaSec docs](https://github.com/brunoos/luasec/wiki), try with some simple example and make sure that is working.

**Comment by chris-jansson** [comment]
Ah, got it. Thanks
